version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    build: .
    environment:
      DB_DRIVER: postgres
      DB_DSN: host=postgres user=postgres password=root dbname=backend_task port=5432 sslmode=disable TimeZone=UTC
      HTTP_ADDR: ":8080"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
