version: "3.9"

services:
  db:
    image: postgres:15
    container_name: backend-db
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend123
      POSTGRES_DB: backenddb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

  app:
    build: .
    container_name: backend-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: backend
      DB_PASSWORD: backend123
      DB_NAME: backenddb
      DB_PORT: "5432"
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge
