version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Database
      POSTGRES_DB: backend_task
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    build: .
    environment:
      DB_DRIVER: postgres
      DB_DSN: host=database-2.c1uuy8cm86e8.eu-north-1.rds.amazonaws.com user=postgres password=Database dbname=postgres port=5432 sslmode=require
      HTTP_ADDR: ":8080"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
