basePath: /
definitions:
  handler.CreateUserReq:
    properties:
      date_of_birth:
        type: string
      email:
        type: string
      name:
        type: string
    required:
    - date_of_birth
    - email
    - name
    type: object
  handler.UpdateUserReq:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: mohammadaliabudalou@example.com
    name: Mohammad Ali Abu-Dalou
  description: REST API in Go (Gin + GORM) with automatic group assignment.
  title: Backend Task API
  version: "1.0"
paths:
  /users:
    get:
      description: List all users, optionally filtered by group (e.g. adult-1, senior-2).
      parameters:
      - description: Group name
        in: query
        name: group
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: List users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Creates new users and assigns them to groups automatically (up
        to 3 per group).
      parameters:
      - description: User info array
        in: body
        name: users
        required: true
        schema:
          items:
            $ref: '#/definitions/handler.CreateUserReq'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/handler.CreateUserReq'
            type: array
        "400":
          description: Invalid request body
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Create one or more users
      tags:
      - users
  /users/{id}:
    get:
      description: Retrieve a user by their UUID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "404":
          description: User not found
          schema:
            additionalProperties: true
            type: object
      summary: Get user by ID
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Update user name and/or email by ID (group cannot be updated manually).
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request or ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: User not found
          schema:
            additionalProperties: true
            type: object
      summary: Update a user
      tags:
      - users
swagger: "2.0"
